# Generated by go2rpm 1.6.0, based on clash.spec in official repo.
%bcond_without check
%global build_timestamp %(date +"%Y%m%d")

# https://github.com/MetaCubeX/Clash.Meta
%global goipath         github.com/MetaCubeX/Clash.Meta

%gometa

%global common_description %{expand:
Another Clash Kernel by MetaCubeX.}

%global golicenses      LICENSE
%global godocs          docs README.md

Name:           clash-meta
Version:        1.13.2
Release:        1%{?dist}
Summary:        Another Clash Kernel by MetaCubeX.
Provides:       clash-meta
Conflicts:      clash-meta

License:        GPLv3
URL:            %{gourl}
Source0:        %{gosource}
Source1:        https://github.com/valig5/fedora/raw/main/clash-meta-bin/clash-meta.service
Source2:        https://github.com/valig5/fedora/raw/main/clash-meta-bin/clash-meta@.service

BuildRequires:  systemd-rpm-macros
BuildRequires:  git

%undefine _missing_build_ids_terminate_build
%global debug_package %{nil}

%description
%{common_description}

%gopkg

%prep
%goprep
sed "s/unknown version/${pkgver}/" -i constant/version.go
sed "s/unknown time/$(LANG=C date -u)/" -i constant/version.go
chmod -x docs/logo.png

%build
go build -o %{gobuilddir}/bin/clash-meta .

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vd                     %{buildroot}%{_userunitdir}
install -m 0755 -vd                     %{buildroot}%{_unitdir}

install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -m 0755 -vp %{S:1}              %{buildroot}%{_userunitdir}/
install -m 0755 -vp %{S:2}              %{buildroot}%{_unitdir}/


%if %{with check}
%check
%gocheck ||:
%endif

%post
%systemd_user_post clash-meta.service
%systemd_post clash-meta@.service

%preun
%systemd_user_preun clash-meta.service
# disable --now seems don't work here.
if [ $1 -eq 0 ] && [ -x /usr/bin/systemctl ] ; then
        # Package removal, not upgrade
        /usr/bin/systemctl --no-reload stop clash-meta@*.service || :
        /usr/bin/systemctl --no-reload disable clash-meta@.service || :
fi

%postun
%systemd_user_postun_with_restart clash-meta.service
%systemd_postun_with_restart clash-meta@*.service


%files
%license LICENSE
%doc docs README.md
%{_bindir}/clash-meta
%{_userunitdir}/clash-meta.service
%{_unitdir}/clash-meta@.service
%gopkgfiles

%changelog
%autochangelog
